### ISSUE TITLE
Ruby 2.2 & 0.6.3 Release

### ISSUE THREAD

**Issue by jalmargyyk** [rails-sqlserver/tiny_tds#196]
It seems that ruby 2.2 compatibility is only in master. Any chance for a new release?

**Comment by metaskills** [comment]
It is not yet easy for me to do the precompiled Windows binaries. If you are on a POSIX system, you can just bundle to master.

**Comment by jalmargyyk** [comment]
Ah, sorry I didn't think other platforms then linux. I prefer to use released gems as this is used in production. Well, I'll just use previous ruby version for the time being. Thanks.

**Comment by aharpervc** [comment]
Referencing master is kind of a hassle when writing a gem (cant reference the repo in a gemspec). And it would be great to have an official release for 2.2. Is there any technical hold up?

**Comment by metaskills** [comment]
> Referencing master is kind of a hassle when writing a gem 

Great points! 

> Is there any technical hold up?

Getting the latest master branch to work with [rake-compiler-dev-box](https://github.com/rails-sqlserver/tiny_tds#compiling-gems-for-windows) for the Windows binaries. Anyone got some free time to debug? I suspect I could make a release for just any system that can compile natively too.

**Comment by metaskills** [comment]
I have pushed 0.6.3.rc1 which is POSIX only. No pre-build win binaries now. HTH!

**Comment by aharpervc** [comment]
A windows build is also necessary. I have attempted to get rake-compiler working for ruby 2.2, not yet successful: https://github.com/rake-compiler/rake-compiler/issues/112

**Comment by aharpervc** [comment]
Good news, I have successfully cross compiled tiny_tds 0.6.3.rc1 for ruby 2.2, for windows. And it works! So getting 0.6.3 released for all platforms for all supported ruby versions for real should totally be possible.

I believe there are only two major blocking issues to make this work. These might be rake-compiler issues or things that can be patched from this repo, not sure. I'm posting my progress here as I work on solutions in case anyone has some quick fixes.

In order to cross compile a gem for ruby 2.2, rake-compiler needs to cross build ruby 2.2. System ruby >= 2.0 is needed to build 2.2, but that's nbd since rake-compiler already acquires ruby 2.0 and 2.1. Rake-compile-dev-box has a prep script to cross build target ruby versions. [Here's the patch to add ruby 2.2](https://gist.github.com/aharpervc/65b3588f5225a118e7a8).

This repo already has a patch for rake-compiler-dev-box to remove 1.8.7 and add 2.1 to the cross-compile version list for win32 fat binaries. We still want to do that basic logic but the patch file is out of date and partially superceded by my patch file. The other part is to update `package_win32_fat_binary` to target 2.2 as a cc version. For testing I removed the other ruby versions and set `RUBY_CC_VERSION` to 2.2.1. Also for testing, I commented out the other ruby versions in `prepare_xrubies` just to save time & focus on 2.2, but they should still work.

Now the first major problem: rake-compiler can't successfully cross build ruby 2.2, as described in [the linked issue](https://github.com/rake-compiler/rake-compiler/issues/112). The situation is that ruby 2.2's securerandom.rb references windows libraries in a way that causes the cross build to fail (it's works differently in 2.1). I don't know the "right" way to solve this problem, but hacking securerandom.rb to wrap the two windows library references in begin/rescue allow the build to succeed (this may not even actually be the worst wrong way to do it, either). [Here's the patch with the hack](https://gist.github.com/aharpervc/e2675cc13ef000d8c791). Don't forget that rake-compiler creates ruby build artifacts in `~/.rake-compiler/build` and `~/.rake-compiler/ruby` that you'll need to remove before re-compiling changes to ruby source files.

So, with these patches, you should be able to cd into rake-compile-dev-box and `vagrant up` and be ready to cross-compile gems for 2.2.

That's all pretty straightforward. The second major issue is a bit more murky and I'm hoping someone will be able to more clearly see what's wrong.

The `rake cross-compile` task fails, because the `package_win32_fat_binary tiny_tds` command fails. The error is due to gemspec validation missing tiny_tds.so. I believe that the compiled `tiny_tds.so` file which is present in `/vagrant/tiny_tds/lib/tiny_tds/` isn't making it into the `pkg` directory. This is causing `package_win32_fat_binary` to fail, which causes `rake cross-compile` to fail. I don't know what part of the process is responsible for copying those files, OR, if something somewhere is looking for `tiny_tds.so` in the wrong place. I'm not sure. To hack my way through and get something working, I modified to manually copy tiny_tds.so into the right places before failing validation, and it worked:

```ruby
# the worst hack ever
# line ~2940  /home/vagrant/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb
`cp /vagrant/tiny_tds/lib/tiny_tds/tiny_tds.so /vagrant/tiny_tds/pkg/tiny_tds-0.6.3.rc1/lib/tiny_tds/tiny_tds.so`
`cp /vagrant/tiny_tds/lib/tiny_tds/tiny_tds.so /vagrant/tiny_tds/pkg/tiny_tds-0.6.3.rc1-x64-mingw32/lib/tiny_tds/tiny_tds.so`
`cp /vagrant/tiny_tds/lib/tiny_tds/tiny_tds.so /vagrant/tiny_tds/pkg/tiny_tds-0.6.3.rc1-x86-mingw32/lib/tiny_tds/tiny_tds.so`
```

Weirdly, I removed these lines later and the rake task worked.... so even worse, I don't know if I caused the problem myself or what the heck is going on. Re-running the rake task, even after clobbering pkg, seems to work. Installing the output x86 gem seems to work and using it in a project in ruby 2.2 seems to work.

Any thoughts, @metaskills ?

**Comment by metaskills** [comment]
INITIAL THOUGHS... OMG! :tada: 

Give me a few hours or so and I will reply in detail.

**Comment by aharpervc** [comment]
Looks like the windows library loading thing was possibly fixed in ruby 2.2.2... so perhaps that patch is not necessary. Giving it a try now...

**Comment by aharpervc** [comment]
Looks like `rake cross-compile` is still blowing up for some reason (possibly different than the 2.2.1 issues). But I manually ssh'd into the rcdb vm and ran `package_win32_fat_binary tiny_tds` which worked successfully (& installs & works with a quick test). I did notice that bundler was missing, and actually I can't find where rcdb is installing bundler for its system rubies. Surely that cannot be the last blocker?

**Comment by aharpervc** [comment]
I created [a fork of rake-compiler-dev-box](https://github.com/veracross/rake-compiler-dev-box) which includes all out standing pull requests required to cross compile tiny tds 0.6.3 for windows including the outdated patch from this repo to remove 187. `rake cross-compile` seems to work fine. I guess my second issue there was also related to 2.2.1? Not sure, but this should mean everything is good to go. cc @metaskills

**Comment by aharpervc** [comment]
@metaskills any chance you'll be able to look at this this week? It'd be great if we could get a full 0.6.3 asap.

**Comment by metaskills** [comment]
Looking now!!!

**Comment by metaskills** [comment]
@aharpervc Thanks for your patience... I was out of town last week :)

I have forked your fork to the rails-sqlserver account, see here https://github.com/rails-sqlserver/rake-compiler-dev-box and you have been added as a collaborator both for that repo and this TinyTDS repo. 

Can you do the updates to this repo to 1) remove the outdated patch and 2) write up some docs on the process in the [Compiling Gems for Windows] section of the README? If so, I would like to test and then we can get these gems released. Afterward, I can even get you added to rubygems.org list too. Cant wait!

**Comment by dicom** [comment]
Any news on this? I would love to see a windows gem release, so that I can upgrade my Ruby environment to 2.2!

**Comment by aharpervc** [comment]
I will be revisiting this in the next couple weeks if @metaskills doesn't get to it first. We want to see a full cross platform 0.6.3 release soon.

**Comment by larskanis** [comment]
tiny_tds Windows binary gems already build great with [rake-compiler-dock](https://github.com/larskanis/rake-compiler-dock) at least on Linux:
```sh
git clone https://github.com/rails-sqlserver/tiny_tds
cd tiny_tds
gem install rake-compiler-dock
rake-compiler-dock bash -c "bundle && rake cross native gem RUBY_CC_VERSION=1.9.3:2.0.0:2.1.6:2.2.2"
```
I don't need rake-compiler-dev-box any more :yum:

**Comment by aharpervc** [comment]
Alright, with c2abdb7 (which points to the updated fork of rcdb) I'm able to `rake cross-compile:setup` followed by `rake cross-compile`, which results in a successful compilation of 32 & 64 bit fat win32 gems which install & work in ruby 2.2.2 in windows. Mission accomplished? @metaskills

**Comment by metaskills** [comment]
Hey @aharpervc !!! I am trying this out today and catching up on #207 The cross-compile failed for me, can you give me any hints as to why? Here is my output https://gist.github.com/metaskills/98076c179f0de82b6c3d and TIA!!!

**Comment by larskanis** [comment]
@metaskills You should be able to cross compile per rake-compiler-dock on OS-X even without #207 . See comment [above](https://github.com/rails-sqlserver/tiny_tds/issues/196#issuecomment-118153772).

**Comment by metaskills** [comment]
Thanks @larskanis made a comment there... will try now too...

**Comment by aharpervc** [comment]
@metaskills from a quick glance at your gist, it appears that maybe the `bootstrap.sh` isn't running. This could possibly happen if the vagrant box already exists, since it won't run provisioner scripts more than once. Can you nuke the old box (or move/rename it) so that it boots fresh?

**Comment by larskanis** [comment]
I tried tiny-tds-0.6.3-rc2 on free versions of Hyper-V Server 2012 R2 with SQL Server Express 2014 with both ruby-2.2.2-x86 and ruby-2.2.2-x64 and the Devkit installed. Per default it installed the fat binary gems, as expected. The test suite raises several failures, similar to [the appveyor results](https://ci.appveyor.com/project/larskanis/tiny-tds/build/1.0.24). Appart from that everything worked fine with both 32 and 64 bits.

Installation with
```sh
gem inst tiny_tds --pre --platform=ruby
```
took some time, but it worked equally well for both 32 and 64 bit environment.

**Comment by metaskills** [comment]
Going to close this out as the 0.7.0 release with Ruby 2.2 will happen by end of the week.
