### ISSUE TITLE
Run ci-tests on appveyor

### ISSUE THREAD

**Issue by larskanis** [rails-sqlserver/tiny_tds#214]
This is just a reminder to add tiny_tds as project to appveyor and to fix/exclude failing tests.

**Comment by metaskills** [comment]
I will have this running today.

**Comment by metaskills** [comment]
Still working on it in the appveyor branch here... for some reason my builds are taking like 40 minutes.

**Comment by metaskills** [comment]
@meet-bhagdev @ajlam I am trying to setup full builds and automated tests for the new awesome Windows binaries. Right now on the free version of Appveyor they are taking 40 minutes and timing out due to the build times. 

https://ci.appveyor.com/project/rails-sqlserver/tiny-tds

I wonder if there is a way to get some sponsorship from Microsoft so that I can fully test both this TinyTDS gem and the SQL Server adapter? TIA.

**Comment by larskanis** [comment]
@metaskills Congrats! Looks like it took a lot of work to get all green. And each build takes annoying 10 minutes on Windows...

**Comment by metaskills** [comment]
This is done. https://github.com/rails-sqlserver/tiny_tds/commit/b52ba291e0c37c7b8e814afa3d6c724edfa4ca05#commitcomment-12516330

**Comment by meet-bhagdev** [comment]
Hello metaskills, 
This is great. Thank you so much for making this work. 
A simple - 'gem inst tiny_tds --pre' command works on Windows and is able to connect to SQL Server and Azure SQL DB. Us folks at Microsoft greatly appreciate this and a big kudos on making work.

Best,
Meet Bhagdev
Program Manager, Microsoft

**Comment by metaskills** [comment]
@meet-bhagdev Is there anyway you can help us start a conversation with Microsoft. Right now I am paying for the CI setup with Appveyor and it would be super cool if we could find a sponsor for these costs. It would be a small amount. Thoughts?

**Comment by meet-bhagdev** [comment]
Hello metaskilss, absolutely. Here is my email: mebha@microsoft.com
I can help you get in touch with people who may be able to help you out with :)
