### ISSUE TITLE
Streaming BLOB columns

### ISSUE THREAD

**Issue by eltiare** [rails-sqlserver/tiny_tds#220]
I'm not sure how to go about streaming BLOB columns from the server using this library. Any hints?

**Comment by metaskills** [comment]
Hey Jeremy, thanks for starting this thread. Could you detail a bit more of your thinking for this. The nature of FreeTDS is to stream tabular data, which includes large data like varbinary columns.

**Comment by metaskills** [comment]
Just found [this article](https://msdn.microsoft.com/en-us/library/hh556234(v=vs.110).aspx). We need to find out if FreeTDS supports this. If so, I would be open to a patch that would allow this. I would imagine we would have to have a new interface that would possible yield an IO object that you would be responsible for serializing some buffer. I'd also like to hear some use cases for this too since we are asking for a new interface to be developed.

**Comment by eltiare** [comment]
@metaskills We're using TinyTDS to get data from a legacy database. They were storing files in the database and I was having trouble trying to get all the data out from them in a memory efficient way. I finally resorted to using SUBSTRING on the column, but that's probably not terribly efficient.

**Comment by endersonmaia** [comment]
I've come into a problem that's maybe related to this. I'm converting a database from SQL SERVER to PostgreSQL, and using [Sequel](https://github.com/jeremyevans/sequel) to do this.

I've opened an issue (jeremyevans/sequel#1132) with them, and according to it, TinyTDS dosn't support returning BLOG data.

**Comment by metaskills** [comment]
@endersonmaia TinyTDS returns all datatypes supported by SQL Server. What we do not do is "stream" binary data by yielding as it comes across the wire. Could you describe that issue on Sequel a bit more please?

**Comment by endersonmaia** [comment]
@metaskills actually, I think is more like a PostgreSQL problem, that is complaining about the byte sequence to not be a valid UNICODE sequence, even the field being `bytea`.

But when I [reported it on sequel](https://github.com/jeremyevans/sequel/issues/1132), I was told the problema was the way Tiny_TDS returned the BLOB data.

This is the data, as captured from Sequel using TinyTDS :

```
irb(main):016:0> sequel_sqlserver_dataset.first[:data]
=> "x\xDA\xCB0\xD4S\b\xCF\xCC\xCE\x04\x00\n)\x02|"
```

And this is the error I get from Sequel using pg adapter : 

`PG::CharacterNotInRepertoire: ERROR:  invalid byte sequence for encoding "UTF8": 0xda 0xcb (Sequel::DatabaseError)`

**Comment by metaskills** [comment]
What is the data type of the column? Also, what type of binary data were you expecting? An image? Something else?

**Comment by endersonmaia** [comment]
It's a gziped data for wiki history content, for the [Redmine](https://redmine.org) application.

**Comment by metaskills** [comment]
What is the datatype of the column? Maybe `varbinary(max)` or something?

**Comment by endersonmaia** [comment]
Yes, `varbinary(max)`.

**Comment by metaskills** [comment]
So we have [solid tests](https://github.com/rails-sqlserver/tiny_tds/blob/master/test/schema_test.rb#L221-L225) for `varbinary(max)`. Perhaps the binary data is being truncated by SQL Server. Sometimes the default is too low. Were you aware there is a client configuration SQL that can set this? We talk about here on the SQL Server Adapter README (https://github.com/rails-sqlserver/activerecord-sqlserver-adapter#configure-connection--app-name) since it comes up often.

**Comment by endersonmaia** [comment]
For what I understood from the last comment on jeremyevans/sequel#1132

> I didn't say this was a problem with tiny_tds per se, just that tiny_tds does not expose an interface that allows customization of the type converters, so Sequel doesn't have a way to automatically convert such columns to use Sequel::SQL::Blob.

If this is a possibility, Sequel would work smoothly in these situations. 

Does that need a new issue, what do you think ?

**Comment by metaskills** [comment]
Discussion on that issue...
