### ISSUE TITLE
time type values returned as Time instances using 1900-01-01 as the date

### ISSUE THREAD

**Issue by jeremyevans** [rails-sqlserver/tiny_tds#274]
This appears to be expected behavior (https://github.com/rails-sqlserver/tiny_tds/blob/master/ext/tiny_tds/result.c#L301).  I guess this isn't really a bug as the SQL Server time type has no date, ruby's Time class requires a date, and therefore any date is fine.  However, I think it may be a little friendlier to use the given time on the current date instead of a date in 1900-01-01.  Not a big deal if you don't think it's worth the effort, feel free to close in that case.

If you'd like me to work on a pull request, I can do that, but I didn't want to prepare one in advance if you don't want to change things.

**Comment by metaskills** [comment]
Hey @jeremyevans, great to hear from ya and thanks for the issue. I actually put some serious thought into this and tried to let the SQL Server data type documentation drive my thinking. See this page for details. https://msdn.microsoft.com/en-us/library/bb677243.aspx

If you search that page, the value `1900-01-01` comes up in quite a few contexts. Without diving into conversions, lower bounds, etc. It felt right to use that value too. The way I saw it, using a static known value would be less surprising than a moving value while being obvious that indeed year/month/day are meaningless and semantic in some other context. 

I'm inclined to stick with it, but interested in what you think and what pains you had with it. Something Sequel related? Cheers.

**Comment by jeremyevans** [comment]
It's not really a big deal to me.  It caused a breakage in Sequel's tests.  I think the current date makes more sense, as it allows easier calculations.  For example, `Time.now - t` to get the difference of the database time from the current time in seconds.

**Comment by metaskills** [comment]
I just checked the MySQL2 gem and they do something similar to us. But they pick the `2000-01-01` value. This seems to be the ActiveRecod convention too places like `quoted_time` of the abstract adapter where they gsub that away. I just remembered that there are coerced tests in the SQL Server adapter because we choose 1900. So I think I am going to keep this issue open and adopt 2000 vs 1900 for our v1 release. 

You feeling that is more standard now?

**Comment by jeremyevans** [comment]
I don't think 2000 vs 1900 makes any difference.  The only difference to me is whether it is the current date or not the current date :).  But like I said, it's not a big deal.

**Comment by metaskills** [comment]
Cool... was hoping to win you over with cross DB gems and ActiveRecord convention. I tried :)

**Comment by sixfeetover** [comment]
Before SQL Server had a dedicated `time` type, you had to store pure time columns as `smalldatetime`. The minimum date for that type is `1900-01-01`, so that's why you see that date when talking about just times in a date+time data type. 

Therefore, using `1900-01-01`, while weird, is probably what most SQL Server users would expect. (I may be projecting here, but it is at least what *I* would expect).

**Comment by metaskills** [comment]
Thanks @sixfeetover, that is exactly the principal of least surprise (for SQL Server users) I was hoping for when thinking about this. I still may change the adapter's types for time to move 1900 to 2000 to be inline with ActiveRecord. But I do think TinyTDS is doing the right thing here from a C extension perspective to SQL Server. Thanks again @jeremyevans
