### ISSUE TITLE
Tiny_TDS in Docker Container

### ISSUE THREAD

**Issue by jgujgu** [rails-sqlserver/tiny_tds#282]
Hello,

I really appreciate the time you've spent building this gem. I've been able to build it into my Rails app on OS X with no problem, but I have had some trouble containerizing it, mainly due to the setup I have to deal with. 

I've successfully run the `make && make install` for FreeTDS inside the container, and I point `tiny_tds` to this source successfully. However, when I get to the FreeTDS install checks, I receive these errors:

```
checking for sybfront.h... yes
checking for sybdb.h... yes
checking for tdsdbopen() in -lsybdb... no
checking for sybfront.h... yes
checking for sybdb.h... yes
checking for tdsdbopen() in -lsybdb... no
```

I tried to remedy this by disabling the Sybase checks.

```
RUN gem install tiny_tds -v '1.0.3' --source http://rubygems.org -- --enable-system-freetds --with-freetds-dir=$FREE_TDS --without-sybdblib
```
But it still checks them:

```
checking for sybfront.h... yes
checking for sybdb.h... yes
checking for tdsdbopen() in -lfalse... no
checking for sybfront.h... yes
checking for sybdb.h... yes
checking for tdsdbopen() in -lfalse... no
```

I understand that the part after "in" is simply a flag and may not have any logic attached to it. `apt-get` is not an option here because it's still on `0.91` of FreeTDS, unfortunately, and I've been blocked for ftp, as I've tried to install the gem by disabling the "system" FreeTDS. 

Is there a step in the FreeTDS installation that I need to fix in order to remedy this? I'm using FreeTDS master.

-Jeffrey

**Comment by metaskills** [comment]
TinyTDS builds against the sydb interface since that is where the DBLIB implementation is. So I would avoid making sydb.h == Sybase vs SQL Server. The interface is the same. 

To your issue... you are going to need to get at least v0.95.80 or higher of FreeTDS installed. How you do that is up to you. I can't offer any platform advice.

**Comment by jgujgu** [comment]
Okay, thank you @metaskills. I will remove those ideas from my mind and try another more robust installation route :D

**Comment by metaskills** [comment]
:)

**Comment by jgujgu** [comment]
For anyone who ever goes down this road...I just downgraded tiny_tds to work with apt-get's freetds-dev and freetds-bin (`0.91`).

```
gem 'tiny_tds', "0.5.0"
```
I am sure the ftp transferred installation works just fine, so I doubt anyone will hit this.

**Comment by metaskills** [comment]
Would not recommend that one since ti is too old. If you had to, I would pick a 0.7.x version or even one of the pre-1.x release candidates. For example `0.9.5.rc.3`. But please please, to anyone else, make an effort to install the latest FreeTDS. You wont get unicode/emoji, new datatypes, or so much unless you do. There has to be a way to do that. Maybe `apt-get install freetds-dev`, custom apt-get repo, or something.
