### ISSUE TITLE
Slow Connections; Not valid win32 Application; OpenSSL

### ISSUE THREAD

**Issue by metaskills** [rails-sqlserver/tiny_tds#310]
We have had several issues with OpenSSL statically linked in the Windows gem. Issues include #250 and #290. Symptoms of using OpenSSL v1.0.x include:

* Slow initial connections.
* tiny_tds.so not a valid win32 application

### Potential Workarounds

* Adding TinyTDS just before Rails starts up, for example above Bundler's setup in boot.rb.
* Setting chcp 866 for tiny_tds.so

### Proposed Next Steps

One of the following two have been proposed.

* Hacks for old OpenSSL. Like using libeay32.dll.
* Use a modern OpenSSL v1.1.0

##### Test Appveyor Build

It would be really nice if we changed our OpenSSL version in extconsts.rb to use 1.1.0.x. I found when doing this that there are some Perl errors on Appveyor because the version is too low. We have a path config set to `SET PATH=C:\MinGW\msys\1.0\bin;%PATH%` and that seems to put a old version of Perl in. I did try adding `SET PATH=C:\Perl\bin` after the MinGW, but it does not seem to add totally fix the issue.

##### Update Docker Usage

I will be doing some CircleCI testing to ensure 1.1.x works for posix systems. However, there is a fair amount of work to make the native `rake gem:windows` tasks work for us to distribute native Windows gems.

**Comment by YvesR** [comment]
Hello @metaskills,
did your tests against Azure pass lately?
I tried 1.0.5 and AR 4.2 and still get the same problem. First connect fails, seconds works then. Also to mention that the 1.0.2g open-ssl still has this CPU bug that loading rails console takes 5 times compared to the fixed libeay32.dll.

bye Yves

**Comment by nmscholl** [comment]
@metaskills 
I am currently experiencing the TinyTDS  Not valid win32 Application error when executing a chef run. In some contexts, I have been able to resolve the problem by requiring TinyTDS in a particular order with the other requirements that use the conflicting components, however I have encountered a situation where this is not sufficient, I still get the error. I attempted to use chcp to resolve the issue as you suggested, however I am unsure what is meant by setting it up "for" a file. Is that different than running it in the same powershell window where tinyTDS will be used? In any case, chcp 866 was used in said powershell window, chef was executed, and the error still occurred. Any information you can provide would be appreciated.

**Comment by coderjoe** [comment]
So I've been poking at this on and off for around a day now, and I can't seem to get around the version constraints of the DevKit environment which prevent OpenSSL 1.1.x from building. My next step would be to move the responsibility of building OpenSSL outside of devkit (so not a part of the rake script), using the build environments available on appveyor, and finally consuming the built library within the tiny_tds build.

What do you guys think, is there any reason for me not to pursue this option? I'm pretty new to these concerns in windows and DevKit so I welcome any suggestions.

**Comment by coderjoe** [comment]
As an aside are there any reasons not to use one of the pre-built openssl libraries for windows mentioned on the openssl wiki? https://wiki.openssl.org/index.php/Binaries

**Comment by metaskills** [comment]
@YvesR Yes, I've run the Azure tests and they are fine. But I am mostly focusing on SQL Server on Linux and hence the latest work in master for it and CircleCI. 

@nmscholl That is the symptom and reason for this issue. The fix that I am proposing is to use OpenSSL v1.1.x but that is not so easy and it requires work that I have not prioritized. @YvesR is suggesting to drop in a different DLL. Both require some work that I have not yet had time to prioritize. 

@coderjoe Neat idea!!! Can we?

**Comment by coderjoe** [comment]
@metaskills honestly, not sure! But I'll keep poking at it. No promises! ;)

**Comment by YvesR** [comment]
@metaskills I have a test env where I do db access directly on start with a initialize script. This fail to start. Starting a console without first db access fails, next and following ones success.

About open SSL 1.1.x: Is it compatible? I read that the openSSL team broke up some compatibilities. So we can just use latest version what @coderjoe suggests?

**Comment by coderjoe** [comment]
@YvesR well my suggestions only really make sense if we're going to OpenSSL 1.1.x... if we keep following the LTS branch (1.0.2x) then it doesn't make sense to change the build system because it shouldn't be necessary yet.

The LTS support branch (1.0.2x) is good until December 31st 2019 so there's no immediate need to switch unless it's the only thing that fixes the binary incompatibility problem on windows. It would be much easier if switching to 1.0.2j fixed it, but I can't get the appveyor tests to pass there. (I notice you're having a similar problem @metaskills in your recent PR)

Honestly 1.1.x or 1.0.2x doesn't matter to me, I'm just desperate to solve this invalid windows binary problem since it's a critical blocker in my work.

**Comment by metaskills** [comment]
> It would be much easier if switching to 1.0.2j fixed it
> I notice you're having a similar problem @metaskills in your recent PR

Yup! See the issue description about `C:\Perl\bin` and such. I have yet to address this. Is there anything I can do to get help with that?

**Comment by coderjoe** [comment]
I meant more in PR #320 , before I started on the OpenSSL 1.1.x path I tried 1.0.2j but ran into the same build problem you are, which seems independent of the Perl version since 1.0.2x doesn't require updated Perl.

As for help, nothing I can think of now, I'm still learning the toolchain and experimenting with permutations so I don't know enough yet to help me ask the right questions. Do you know of any good guides/resources on setting up test VMs to test/verify tiny_tds on windows? Right now I'm working off of a Windows 10 Evaluation VM I set up to help me out.

**Comment by YvesR** [comment]
Well my main concern about openSSL is the bug on windows that it causes 100% CPU usage for no reason. A rails console starts in like 4 seconds on my dev machine. With 1.0.2.x openSSL on windows, which still has the bug, it needs like 15 seconds with big CPU usage.

**Comment by coderjoe** [comment]
@YvesR I just spent a good part of a day hacking on this trying to get it to work. Have you verified that OpenSSL 1.1.0 is supported by freetds? From everything I can tell it relies on direct struct access to BIO information in SSL which isn't accessible anymore in OpenSSL 1.1.0. It also relies on defineds that no longer exist in 1.1.0.

I'm starting to think OpenSSL 1.1.0 just is not an option until upstream sources start building for it.

**Comment by YvesR** [comment]
@coderjoe I never dig so deep to check about FreeTDS itself. I tried to build tinyTDS on ym dev machine, but failed to modify the build task with latest OpenSSL build. In #250 you can read that we manually replaced the libeay32.dll. I took the DLL provided by @lukajandric and manually replaced it in tinyTDS 0.7.0. That did not work in a 0.9.x release but works again in 1.0.5. So I work with the latest 1.0.5 gem and manually replaced the libeay32.dll there.

**Comment by metaskills** [comment]
@YvesR Can you post a link to that DLL? Would we be able to add that to the repo here and cp it over during build time for Windows till the longer 1.1 plan can be worked on?

**Comment by YvesR** [comment]
Yes, sure, it was posted first time in #250.
But here again: [https://github.com/rails-sqlserver/tiny_tds/files/234289/libeay32.zip](libeay32.zip)

**Comment by coderjoe** [comment]
FWIW, after reading the OpenSSL patch info, it would seem like they aren't patching OpenSSL because Microsoft released a hotfix. In my opinion, installing the hotfix on affected machines is preferable to maintaining an unsupported/patched version of OpenSSL which could open the project up to other bugs.

@YvesR would this hotfix address your problem?

https://support.microsoft.com/en-us/kb/2719306

**Comment by YvesR** [comment]
@coderjoe sadly no. The bug is not fixed by Microsoft. It still happens on Windows 2012 R2 and Windows 2016! I run 2012 machines, not 2008 anymore. Dev 2016 machines I run have same issue, too.
So in fact the issue is solved by the lib from the link I posted and not fixed without on any current windows machine.

**Comment by coderjoe** [comment]
@YvesR that's extremely unfortunate. Have you opened an incident with Microsoft? You might have to.

Looking at the patch it would seem the patch may be dangerous. It seems to suggest that by moving from `Heap32First` and `Heap32Last` to `HeapWalk` that you limit the heaps being walked to only the current process's heap. That seems like a tremendously bad idea since the heapwalk is helping seed the random number generator with entropy...

To quote the second post in the patch info discussion:

> But the RAND code in openSSL is using the heap walking to get as many 
random allocation details as possible from all processes in the system 
to seed its RNG. 
> So limiting the RAND code to only a single heap from its own process 
will effectively make that code useless and severely weaken the security 
of all cryptographic keys and nonces produced by openSSL.  It is simply 
not an option. 

http://openssl.6102.n7.nabble.com/Deadlock-in-RAND-poll-s-Heap32First-call-td13043.html

I would caution against using the patched binary. Speeding up startup by a few seconds is not worth compromising OpenSSL's entropy.

**Comment by coderjoe** [comment]
@YvesR as an aside, how large is the combined heap on your machines? I haven't been experiencing these slow startups and I'm wondering if it's just because of a smaller system heap. Could it be it is taking so long because there is a lot of heap to walk and that's just how long it takes?

The bug the patch fixes is not a slow startup, it's a deadlock which would imply you are not hitting that bug if your application eventually starts.

**Comment by YvesR** [comment]
@coderjoe My application which has the problem has some config/intializer scripts where I read data from database at startup. That is probably the reason why I run into this bug from start.

I run a dev machine on my MacBook on VMware Fusion which runs Windows 2012 R2 with 4 Cores and 8GB RAM.

- Rails v4.2
- Ruby 2.0.0p598
- tinyTDS 1.0.5
- activerecord-sqlserver-adapter 4.2.15

- Using not fixed DLL => 10,63 seconds to load "rails c". While 80% of the time 100% CPU usage on this core that runs the ruby.exe.
- Using fixed DLL => 4,26 seconds while I never hit 100% CPU usage on that core.

I am not experienced that deep but the CPU load and time speaks for itself that this has to be addressed.

**Comment by coderjoe** [comment]
@YvesR I agree that your problem should be addressed, but I do not believe the patch you have provided is the best way to go about it.

Frankly, I am not comfortable with the patch and its potential security implications, and if you're patching core Ruby with this DLL to speed up load times I would recommend only doing it in development, not in production.

**Comment by coderjoe** [comment]
So I've hacked together some changes using OpenSSL 1.0.2j and freetds 1.00.21 which result in binaries which appear to avoid the invalid win32 executable error as well as the error 998: invalid memory access error.

How would you like to go about reviewing this? Just submit a pull request for review? It has some not-so insignificant changes.

**Comment by coderjoe** [comment]
@metaskills what are the chances I could get an ETA review on #322? If my changes aren't acceptable I can work towards an alternative. 

I don't want to rush you but the invalid win32 executable is a production blocker at work. :(

**Comment by metaskills** [comment]
Just did that now and also added you as a collaborator. Cheers!

**Comment by YvesR** [comment]
Awesome job @coderjoe, so if you want me to make some tests on windows I will help. Just tell when and what you want me to test.

**Comment by coderjoe** [comment]
@YvesR if you get some time I'd love it if you could test the gem source in my pull request above. If you can't build the gem locally let me know and I can produce a binary for you. I'm curious what the load times are like with this update.

**Comment by YvesR** [comment]
I used to built it with the Docker environment. This will work here too? Else if you don't mind and you build it I can test it against my dev and some test machines, including Azure.

**Comment by coderjoe** [comment]
@YvesR yep, if you build via `bundle exec rake gem:windows` from rake-compile-docker it should generate valid win32 executables. I run linux at home and that's how I built it. If for any reason you run into problems please let me know so I can investigate. :)

**Comment by coderjoe** [comment]
Alternatively it _should_ also build from within windows using RubyInstaller + DevKit.

**Comment by YvesR** [comment]
Ok I will try and let you know the results asap.

**Comment by coderjoe** [comment]
@YvesR I've built some windows binaries from my work in progress and hosted them on Google Drive so you won't have to build them yourself. Hope this helps!

https://drive.google.com/open?id=0BxSqGuxD46a2SERYYW12TTdFOHM

**Comment by YvesR** [comment]
@coderjoe Rails console loading did not change in time and CPU usage with your latest gem. I tried the 64bit version in my system. Installed your gem locally (btw: getting ASCII to UTF8 convert errors with the local gem on install, probably in ri documentation install) and then compared 1.0.5 and 1.0.6. Same status. Used my "modified" dll with 1.0.5 to cross check, there it reacts like described earlier above.

Also tried 1.0.5 and your 1.0.6 from one of my development machines against SQL Azure DB. In both cases (@metaskills said his Azure tests pass so I still do not know what is going on):

```
d:/Informer/ruby/lib/ruby/gems/2.0.0/gems/tiny_tds-1.0.6-x64-mingw32/lib/tiny_tds/client.rb:53:in `connect': Adaptive Server connection failed (grsx6ycyxh.database.windows.net:1433) (TinyTds::Error)

```
To mention that I do a database access already on startup the rails console having config/initializers/constant.rb which loads parameters from the database.

**Comment by coderjoe** [comment]
@YvesR thanks for testing!

**Regarding ASCII to UTF8 conversion errors**: If you have any idea how I can reproduce these conversion erros that would be great. I haven't seen them so I'm not really sure what to fix.

**Regarding the slow/CPU issue**: I'm starting to doubt I'll be able to address that problem in this patch. I have one idea, but it's a long shot. I'll try and throw together another testing branch for you to try on my lunch break today.

**Regarding Adaptive Server connection failed**: My only experience with that is when the server isn't set up to accept connections or when a firewall was blocking the connection attempt. Are you using `:dataserver` or a `:host` and `:port` combo to configure your TinyTds connection? If you're using `:dataserver` try switching to `:host` and `:port`. If you're already using `:host` and `:port` then it's usually a sign that freetds was unable to connect to MSSQL. Check that it's set up to receive remote connections, that there are no firewalls in your way, etc.

**Comment by YvesR** [comment]
**Regarding ASCII to UTF8 conversion errors:**
![bildschirmfoto 2016-12-06 um 16 08 29](https://cloud.githubusercontent.com/assets/4928882/20930609/57e40ab0-bbce-11e6-83c3-1101567fe86c.png)
Have no clue if this is a problem or just to ignore :)

**Regarding the slow/CPU issue:**
I can't really say what this issue is. the environment is loading for like 2 seconds, then I/O stops and CPU raise to max for the core. The usage is like 6-7 seconds, then it continue to load the environment. After system is loaded no more problem. 
Maybe at some point the library is used to generate some random string and this causes the issue? 

**Regarding Adaptive Server connection failed:**
As I already mentioned when loading rails console or production I habe a config/initializers/const.rb that makes a DB access.

Example:
```
PROPS = LegacyProperty.first
ENV['INFORMER_COMPANY'] = INFORMER_COMPANY = PROPS.companyname.to_s.strip
```
**So on loading I already do database access.**

I did comment this file and set all the ENV[''] manual so I do not have DB access on start. In this case my rails console loads even with Azure connection.

Then check the following screenshot. The first connect fails with `Write to server failed` while the second and all other attempts works!
![bildschirmfoto 2016-12-06 um 16 27 58](https://cloud.githubusercontent.com/assets/4928882/20931514/9f7b94ee-bbd1-11e6-8621-25ba48e26288.png)

**I just realized that my CPU usage and loading is not happening without db access.**

**Comment by coderjoe** [comment]
@YvesR thanks again for the information. This is very helpful. I think I know how to fix the ASCII to UTF8 conversion errors. It looks like you're using Ruby 2.0 which (if I remember correctly) uses an old rdoc which would throw these errors when it encountered binary files during documentation generation.

I'm still not sure what to do about your other errors I really wish I could help more but I don't currently have the knowledge I'd need to assist and I don't yet know what to ask for. Maybe as I work through finishing up the patch for the win32 invalid executable error I'll think of more.

**Comment by YvesR** [comment]
@coderjoe 
- Yes, I work with ruby 2.0.0p598 at the moment.

@metaskills 
- So far I can be sure that the CPU usage is from the very first connection from tiny_tds.
- On a non azure database I just have high CPU usage while connection works.
- On azure database the very first attempt always fails while all following connections works.

I am not sure if this is just because of Azure. I will setup a local database with encrypted connection and check if this will work or the first connection fails also (which I guess it does).

**Comment by metaskills** [comment]
Thanks for the update. I was hoping @coderjoe's work would have fixed the CPU usage on first connection, however, I do want to move forward with it even if it does not. 

**Regarding "Write to the server failed" Messages** I think we should track that issue/work on https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/446 or https://github.com/rails-sqlserver/tiny_tds/issues/249 since I think those issues are more focused.

**Comment by hbuckle** [comment]
I have been running into the cannot load win32 invalid executable error when using tiny_tds from a Puppet module, but 1.0.6 from @coderjoe appears to resolve this issue at least.

**Comment by coderjoe** [comment]
@metaskills what's on the docket for 1.0.6? Is there anything I can do to help get that out the door?

**Comment by metaskills** [comment]
@coderjoe Just this... I was trying to build native gems and fell flat. I feel like 1.0.6 or better yet 1.1 should have #324 done.

**Comment by coderjoe** [comment]
@metaskills I presume by this you mean just the slow connection bug, and not OpenSSL 1.1?

**Comment by YvesR** [comment]
@coderjoe I try work on #249 (connection bug) here with some colleagues...

**Comment by metaskills** [comment]
Just released v1.1.0. Please test with that.

**Comment by YvesR** [comment]
@metaskills I doubt you address me with the test, but I did anyway :)
- Local system: Works as usual, no error
- Local system with SSL encrypted SQL server: Works without error
- CPU usage on load: Same as before, but you didn't address this with 1.1.0 I guess
- Azure connect: 1st connect fails, 2nd attempt works

**Comment by hbuckle** [comment]
1.1.0 has been fine for me so far, no win32 invalid executable errors

**Comment by metaskills** [comment]
Just noticed this commit in FreeTDS (https://github.com/FreeTDS/freetds/commit/bbe6d1bbe3ce3c6d7a89e8d883ccfc4f8c19f572) which says "Provide compatibility with OpenSSL 1.1". So this seems ripe to try again now to move from OpenSSL v1.0 to v1.1

**Comment by YvesR** [comment]
@metaskills In the build scripts we can just change the versions to compile so it fetches the correct sources or does the tiny built process needs to be modified?

**Comment by metaskills** [comment]
Yup, making a PR with that change will tell us if that works. Simple change in extconsts and a few other places. See #322 for reference.

**Comment by metaskills** [comment]
Oh... we may have to wait till FreeTDS has a release... I'd have to check this distills to see what version that has. Likely might be a day or so since that commit just landed.

**Comment by YvesR** [comment]
Ok, let us wait until that and I will try it then. Hopefully they are ready until weekend. Good time for tests :).

**Comment by metaskills** [comment]
FYI, tried to take a look at this today and I noticed the FreeTDS FTP site was down. I sent an email to their mailing list. Will try again in a few days.

**Comment by YvesR** [comment]
Did you manage to compile? I change `extconst.rb`this weekend to open ssl 1.1.0e and freetds to 1.0.27 and modified `extconf.rb`to

        execute "mkdef-libeay32", "(perl util/mkdef.pl 32 crypto >libeay32.def)"
        execute "mkdef-ssleay32", "(perl util/mkdef.pl 32 ssl >ssleay32.def)"

Also update my docker image to rake compile 0.6.0. For testing I compiled with original config. Works fine. With modified settings openssl compile worked but freetds failed to build.

My Logfile: https://gist.github.com/YvesR/098ad10b6222f83d7c4204ef64bfc24c

**Comment by metaskills** [comment]
The branch/pr #344 is where I am working on that. Comments and help there welcome.

**Comment by metaskills** [comment]
PR #374 got a good build (from what I can tell) of OpenSSL 1.1 for Windows. I just published `v1.2.0.beta1` from that branch. Please give it a try.

**Comment by YvesR** [comment]
I pulled https://github.com/rails-sqlserver/tiny_tds/pull/347 and did run `rake gem:windows`

Compile works so far, that is awesome.
But in the final stage to make the package I get this.

<details>

```
mkdir -p pkg/tiny_tds-1.1.0/ports/archives
rm -f pkg/tiny_tds-1.1.0/ports/archives/freetds-1.00.27.tar.bz2
ln ports/archives/freetds-1.00.27.tar.bz2 pkg/tiny_tds-1.1.0/ports/archives/freetds-1.00.27.tar.bz2
cd pkg/tiny_tds-1.1.0
mv tiny_tds-1.1.0.gem ..
cd -
rake aborted!
Don't know how to build task 'ports/i686-w64-mingw32/bin/libcrypto32-1.1.0e-i686-w64-mingw32.dll' (see --tasks)
/usr/local/rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => gem => pkg/tiny_tds-1.1.0-x86-mingw32.gem
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [docker run -v /Users/rausch/Documents/_Projekte/tiny_tds:/Users/rausch/Documents/_Projekte/tiny_tds -e UID\=1000 -e GID\=1000 -e USER\=rausch -e GROUP\=_staff -e ftp_proxy\= -e http_proxy\= -e https_proxy\= -e RCD_HOST_RUBY_PLATFORM\=x86_64-darwin15 -e RCD_HOST_RUBY_VERSION\=2.3.1 -e RCD_IMAGE\=larskanis/rake-compiler-dock:0.6.0 -w /Users/rausch/Documents/_Projekte/tiny_tds --rm -i -t larskanis/rake-compiler-dock:0.6.0 runas sigfw bash -c \ \ \ \ bundle\ \&\&\ rake\ cross\ native\ gem\ RUBY_CC_VERSION\=2.4.0:2.3.0:2.2.2:2.1.6:2.0.0\ CFLAGS\=\"-Wall\"'
']
/Users/rausch/Documents/_Projekte/tiny_tds/Rakefile:91:in `block in <top (required)>'
Tasks: TOP => gem:windows
(See full trace by running task with --trace)
```

</details>

On some point the copy of the compiled stuff do not copy the necessary files.

![screen1](https://cloud.githubusercontent.com/assets/4928882/23601896/0b2d2212-024e-11e7-88f5-a45d4fa79bdf.png)

![screen2](https://cloud.githubusercontent.com/assets/4928882/23601899/0f8c2d62-024e-11e7-89e1-e9f37c86a5e8.png)

**Comment by metaskills** [comment]
Can you check the v1.2.0.beta1 gem published to rubygems? Does it exhibit the same behavior?

**Comment by YvesR** [comment]
Do you have the link? when I `gem install tiny_tds.1.2.0.beta1.gem` I get error that it is not found.

**Comment by metaskills** [comment]
I would add the version to Bundler. You would need a `-v` arg if you wanted to target a specific version. I tend to use `--pre` tho:

```shell
$ gem install --pre tiny_tds
Fetching: tiny_tds-1.2.0.beta1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed tiny_tds-1.2.0.beta1
1 gem installed
```

But again, I would add the version to my Gemfile and bundle.

**Comment by YvesR** [comment]
Yeah, did a modify on my gemfile and bundle install. Worked fine after fix my cert-problem.

And now the good news first or the better news :)?

**The good news: rails console opens without high CPU load anymore and much faster then before**

**The better news: rails works with Azure SQL now without the previous issues**

Open champagne, you earned it! :) I will do more tests now and seek more into it...

**Comment by metaskills** [comment]
Huge thanks to @orgads!!!

**Comment by orgads** [comment]
I'm glad to see it works :)

**Comment by metaskills** [comment]
Pull Request #347 pulled in OpenSSL v1.1.0 and we got new versions of TinyTDS at v1.2.0 which should solve this issue. Please reply back and let us know.
