### ISSUE TITLE
Can't compile the native extensions even with freetds installed

### ISSUE THREAD

**Issue by teaearlgraycold** [rails-sqlserver/tiny_tds#326]
I'm running Debian 8 and freetds v1.00.23, and any version of tiny_tds causes me to experience build errors. The installation process claims that I don't have freetds installed.

I've tried installing freetds from the debian repos, as well as from freetds.org as documented in this project's readme.

I can see in the build log that tiny_tds attempts to install an older version of freetds unsuccessfully first, and then complains about the missing dependency.

**Comment by teaearlgraycold** [comment]
I was wrong with the title - somehow I'd had 1.0.2 install successfully before, but after uninstalling it I can't reinstall it. So it seems I'm unable to run any version of tiny_tds.

**Comment by phulst** [comment]
I ran into similar (or the same) issues, on Ubuntu 16.04 though. Neither a manual install of freetds  from source nor the version that tiny_tds attempts to build and install were working. I tried using the --with-freetds-include and --with-freetds-lib options to point to the right directories, but I now believe that the tiny_tds gem did not follow those instructions properly. 

The old versions of the freetds-dev and freetds-bin packages (version 0.9x), that were installed through the package manager, turned out to be the issue. Somehow tiny_tds was still trying to compile against those, despite all the configuration options I had tried. 

After removing these packages with  'sudo apt-get remove freetds-dev freetds-bin'  the tiny_tds gem compiled and installed fine. Hope this helps.

**Comment by phulst** [comment]
on Ubuntu the latest officially supported versions of freetds appears to be 0.91. If you install freetds-dev and/or freetds-bin with apt-get, you won't be able to install tiny_tds >= 1.0, at least that was my experience. So remove those packages first before installing tiny_tds. Building freetds from source is probably not necessary unless you need a customized version or need the binaries/libraries outside your rails app as well.

**Comment by teaearlgraycold** [comment]
@phulst thanks! That worked for me.
