### ISSUE TITLE
Connect MSSQL using Windows Authentication

### ISSUE THREAD

**Issue by Midacts** [rails-sqlserver/tiny_tds#337]
irb(main):003:0> client = TinyTds::Client.new username: 'username', password: '********', host: 'servername'
/opt/rh/rh-ruby22/root/usr/local/share/gems/gems/tiny_tds-1.1.0/lib/tiny_tds/client.rb:53: warning: TinyTds: :use_utf16 option not supported in this version of FreeTDS.

TinyTds::Error: Login failed. The login is from an untrusted domain and cannot be used with Windows authentication.
        from /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/tiny_tds-1.1.0/lib/tiny_tds/client.rb:53:in `connect'
        from /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/tiny_tds-1.1.0/lib/tiny_tds/client.rb:53:in `initialize'
        from (irb):3:in `new'
        from (irb):3
        from /opt/rh/rh-ruby22/root/usr/bin/irb:11:in `<main>'

--------------------------
Issue #236 is the same but it is closed.
I am runny ruby in Red Hat CLoudforms and will be unable to setup Credential Manager or use a runas.
Does that mean there is not an "easy" alternative?

**Comment by Midacts** [comment]
It's not something that is going to work? 
: [

**Comment by metaskills** [comment]
What version of FreeTDS did you compile against? Use `$ tsql -C` to show.

**Comment by Midacts** [comment]
# FREETDS INSTALL
wget ftp://ftp.freetds.org/pub/freetds/stable/freetds-1.00.21.tar.gz
tar -xzf freetds-1.00.21.tar.gz
cd freetds-1.00.21
./configure --enable-sspi
make
make install 

# TINY_TDS INSTALL
# Created CentOS-7 - SCLo repo, so that it can pull packages from internet
yum install rh-ruby23-ruby-devel
gem install tiny_tds --source http://rubygems.org/ 
(we need to use the RHEL 7 "rh-ruby23-ruby-devel" repo instead of Centos repos)

# TSQL -C
[TinyTds][v1.1.0][tsql]: /usr/local/bin/tsql
Compile-time settings (established with the "configure" script)
                            Version: freetds v1.00.21
             freetds.conf directory: /usr/local/etc
     MS db-lib source compatibility: no
        Sybase binary compatibility: no
                      Thread safety: yes
                      iconv library: yes
                        TDS version: auto
                              iODBC: no
                           unixodbc: no
              SSPI "trusted" logins: no
                           Kerberos: no
                            OpenSSL: no
                             GnuTLS: no
                               MARS: no

**Comment by metaskills** [comment]
Thanks, a few thoughts:

1) The fact you got the warning about `use_utf16` gives me some concern. You show that you installed v1.00.21 which supports that option but I wonder if TinyTDS actually linked to that version. Perhaps you can check you compiled binary with a  linking tool like `otool` to see what version it linked to.https://github.com/rails-sqlserver/tiny_tds/blob/master/ext/tiny_tds/client.c#L347-L354

2) Your issue says "using Windows Authentication" but I am not super familiar how FreeTDS does this on non-Windows systems. Have you read up on that (http://www.freetds.org/userguide/domains.htm) and made sure you can actually connect in that manner using `tsql` first?

**Comment by redbar0n** [comment]
1. It may be that a previously installed tiny_tds version linked to an old FreeTDS version. After installing a FreeTDS version > v1.00.21 then I still got the use_utf16 warning in the rails console. I got it even if I ran `gem uninstall tiny_tds` (which only uninstalls it from the global system gemset). Turns out you have to remove tiny_tds from the `<app_root>/vendor/bundle/ruby/2.3.0/gems/` path so that the previously compiled binary rails will use when running is removed as well. So only after running `bundle exec gem uninstall` which removed this, and running `bundle install` again, to recompile the binary with the newly linked FreeTDS version and add it again to the vendor bundle, did it remove the use_utf16 warning in the rails console for me. 

Hope this may help someone else stumbling across this problem.
