### ISSUE TITLE
Backtrace when running transaction

### ISSUE THREAD

**Issue by grejon04** [rails-sqlserver/tiny_tds#338]
I seem to intermittently get an unhandled exception when running transactions wrapped in TinyTDS - I've seen this with both version 1.0.2 and 1.1.0 of the gem, as downloaded from the CentOS yum repo.

Also, very concerning in this code, TinyTDS does not seem to ever pass errors or query information back up to the result class - the statements are executed, but the information is not passed back in the result object.

System info, stacktrace, and supporting code attached.

[tt-backtrace.txt](https://github.com/rails-sqlserver/tiny_tds/files/729748/tt-backtrace.txt)
[tt-code.txt](https://github.com/rails-sqlserver/tiny_tds/files/729749/tt-code.txt)
[tt-system-info.txt](https://github.com/rails-sqlserver/tiny_tds/files/729750/tt-system-info.txt)
[tt-dbconnect-code.txt](https://github.com/rails-sqlserver/tiny_tds/files/729754/tt-dbconnect-code.txt)

**Comment by metaskills** [comment]
Whoa... sorry for the slow reply, I missed this one.

> TinyTDS does not seem to ever pass errors or query information back up to the result class

Rest assured we have tests and this does indeed work. The adapter would not get very far if this was not true. On to your problem. But first, a bit of critique on your code. Please don't take this the wrong way, but you have over complicated and done a lot of work for connections and executing statements that Rails does for you. May I suggest that you work on two areas to help fix things up.

### Code complexity. 

Please use a simple `abstract_class` sub class and use `establish_connection`. See this article I wrote "Topic 1" on how to do this. http://technology.customink.com/blog/2015/06/22/rails-multi-database-best-practices-roundup/ By doing so, you can avoid the super complex code of managing transaction which your code is lacking. If you really want to writ you own connection management and SQL buffers, please consider using gems that are tested and do that in isolation. But since you already have Rails in your stack – please use that :)

### FreeTDS Version

I see you have an older version of FreeTDS installed `v0.95.81` with a really old default TDSVER. Tho technically mentioned in the docs, would you mind please trying the latest 1.0 and trying configuring with the `--with-tdsver=7.3` option. That said, I do think your problem lies mostly in your own code.

Can you let me know how that goes or if you think I am missing something?
