### ISSUE TITLE
Can you run UPDATE queries using TinyTDS?

### ISSUE THREAD

**Issue by stevelake** [rails-sqlserver/tiny_tds#355]
I'm trying to update a column in an SQL Server d/b in my ruby code using TinyTds - without success. When I take a copy of the query and run it manually using SQL Server Management Studio the update works fine, so I guess the syntax must be OK. I have no problem connecting to the d/b from my ruby code to run SELECT queries. It occurs to me that there's no specific mention of performing an UPDATE in the TinyTDS documentation, so I'm starting to think it may not be possible. Can anyone confirm one way or the other?

I'm running on Windows 10 and using TinyTDS version 1.0.5 x86-mingw32

**Comment by metaskills** [comment]
The Rails adapter uses TinyTDS exclusively and without UPDATES we could nog get far :) so yea, it works. Would you mind posting the statement you are using and the error that happens? Cant get far helping without it. In general, any T-SQL is fine for TinyTDS. Only issue I have seen is where people use the `GO` statements which is fine for the SMS but is not in the DBLIB protocol layer. HTH.

FYI, This projects README even suggests that UPDATE/DELETE (tho only DELETE is exemplified) and if you dig in the tests (specifically result test) you will see UPDATE based assertions. I only mention because sometimes it is helpful to find this stuff on your own vs wait for a email, GitHub, or other reply.

**Comment by stevelake** [comment]
Thanks for getting back to me so quickly! I'll certainly dig into the documentation a little deeper. As for my original update query, I gave up on it and can't find my note of it but at least now I know it should work.
