### ISSUE TITLE
Getting a weird Tinytds error

### ISSUE THREAD

**Issue by sithara** [rails-sqlserver/tiny_tds#357]
This is an update statement - which throws the below error when executed . I havent used LEFT or Substring hence cannot understand what the error means

TinyTds::Error: Invalid length parameter passed to the LEFT or SUBSTRING function.: EXEC sp_executesql N'UPDATE [table] SET [status_description] = N''Completed successfully'', [status] = N''completed'', [updated_at] = ''2017-05-18T02:33:13.387'' WHERE [table].[id] = 23369; SELECT @@ROWCOUNT AS AffectedRows'

The table gets updated though

I'm using tiny_tds version 0.7.0 and have got no triggers in my database . It is through a state machine that this query gets generated

**Comment by metaskills** [comment]
Sorry for the late reply. Did you have any more info on this since posting? A trigger would have been my first guess. Especially if this is a legacy DB not setup by Rails. To debug, I would execute the inner statement in decreasing complexity via SMS or a raw execute to see if any different behavior shows up.

**Comment by sithara** [comment]
Thank you :+1:

**Comment by smesh** [comment]
@sithara , was this trigger?
