### ISSUE TITLE
LoadError: cannot load such file -- tiny_tds/tiny_tds

### ISSUE THREAD

**Issue by WilliamJones62** [rails-sqlserver/tiny_tds#388]
I have written a Ruby on Rails app on Windows 10 that uses SQLite3 in development but needs to use SQLServer in production. I am using Ruby 2.3.3 and Rails 5.1.4. I included the tiny_tds and activerecord-sqlserver-adapter gems in the Gemfile and ran 'bundle install'. This seems to have completed successfully. I then ran 'rails db:migrate RAILS_ENV=production'  and got the error 'LoadError: cannot load such file -- tiny_tds/tiny_tds'. The complete error message output is below. Can you please tell me what the problem may be and what I can do to fix it.

$ rails db:migrate RAILS_ENV=production
rails aborted!
LoadError: cannot load such file -- tiny_tds/tiny_tds
c:/Sites/turkeytote/config/application.rb:7:in `<top (required)>'
c:/Sites/turkeytote/Rakefile:4:in `require_relative'
c:/Sites/turkeytote/Rakefile:4:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
LoadError: 126: The specified module could not be found.   - c:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds/2.3/tiny_tds.so

**Comment by WilliamJones62** [comment]
I should have mentioned that the file c:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds/2.3/tiny_tds.so is present.

**Comment by WilliamJones62** [comment]
Do I need to install FreeTDS?

**Comment by aharpervc** [comment]
Didn't 2.1.0 bump the minimum supported ruby to 2.4?

**Comment by WilliamJones62** [comment]
Do you think that if I use the latest version of Ruby that this problem will go away? Also where can I download a windows version of FreeTDS?

**Comment by aharpervc** [comment]
I don't know if there is a release of activerecord-sqlserver-adapter that will be compatible with *both* Rails 5.1 and TinyTds < 2.1.0, so you might *have* to upgrade ruby. That would definitely be the first thing to try and might sidestep other problems.

Also, per the readme:

> Windows users of our pre-compiled native gems need not worry about installing FreeTDS and its dependencies.

That's your case, so you shouldn't need to independently track down freetds.

**Comment by WilliamJones62** [comment]
Thanks for your help. I am using railsinstaller to install both rails and ruby. The latest version of ruby is 2.3.3. Do you know how I can install ruby 2.4 so that it will work with rails without using railsinstaller?

**Comment by aharpervc** [comment]
I'm not familiar with railsinstaller, sorry. Looks like there's an issue discussing 2.4.1 here: https://github.com/railsinstaller/railsinstaller-windows/issues/96. It's possible to get 2.4.1 separately yourself, of course, but I have no idea how that might disrupt your railsinstaller environment.

**Comment by aldent95** [comment]
+1 for this issue.
I don't suppose there is a way around this without upgrading to Ruby 2.4? I've tried that but there is another gem, nio4r, that fails to build for me in Ruby 2.4.

**Comment by WilliamJones62** [comment]
Is there a version of tiny_tds that works with ruby 2.3.3?

**Comment by WilliamJones62** [comment]
I just went to RubyGems.org and looked at tiny_tds. For the latest version the requirement is for ruby < 2.5, >= 2.0, not v2.4. Is this a typo? I looked at version 1.3 it requires ruby >= 2.0.0. Would this be okay to use?

**Comment by WilliamJones62** [comment]
I used the V1.3.0 of tiny_tds and my problem went away.

**Comment by metaskills** [comment]
> I just went to RubyGems.org and looked at tiny_tds. For the latest version the requirement is for ruby < 2.5, >= 2.0, not v2.4. Is this a typo?

When I look at Rubygems I see what is in our gemspec. `REQUIRED RUBY VERSION: >= 2.0.0` so technically what you said is right and wrong >= 2.0 does indeed include 2.4 too. We even test on 2.4 via Appveyor, I've done it locally too. We even test on 2.1 via TravisCI and CircleCI. Lastly, I even rand a clean Ruby 2.0 test too and everything seems fine. So the required ruby version seems just fine to me. Is anyone suggesting a change?

FYI, the required Ruby version for Rails v5.1 (which has no bearing on this gem) is Ruby `>= 2.2.2`. So that or 2.3 as stated by @WilliamJones62 is just fine.

> I used the V1.3.0 of tiny_tds and my problem went away.

@WilliamJones62 it would be nice to use the latest v2.1 of TinyTDS. Do you think your issues is related to [this section](https://github.com/rails-sqlserver/tiny_tds#install) of our docs which state:

>  If you're using RubyInstaller the binary gem will require that devkit is installed and in your path to operate properly.

**Comment by aharpervc** [comment]
>  Is anyone suggesting a change?

I think the observation was simply that TinyTds 2.1.0 doesn't work ruby < 2.4, which matches my experience. I thought the minimum version had been bumped at some point. If not, we might have a problem somewhere.

**Comment by metaskills** [comment]
@aharpervc But it does work with Ruby < 2.4 on many platforms tested locally and with CI. What am I missing?

**Comment by aharpervc** [comment]
It manifests the same way as various other issues in the past, where the library apparently can't be loaded:

```log
$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [i386-mingw32]

$ gem list tiny_tds

*** LOCAL GEMS ***

tiny_tds (2.1.0 x86-mingw32, 2.0.0 x86-mingw32, 1.3.0 x86-mingw32, 1.0.5 x86-mingw32)

$ irb
irb(main):001:0> require 'tiny_tds'
=> true
irb(main):002:0> TinyTds::VERSION
=> "2.1.0"
irb(main):003:0> exit
```

Compared to:

```log
$ ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]

$ gem list tiny_tds

*** LOCAL GEMS ***

tiny_tds (2.1.0 x86-mingw32, 1.0.5 x86-mingw32, 1.0.4 x86-mingw32)

$ irb
irb(main):001:0> require 'tiny_tds'
LoadError: cannot load such file -- tiny_tds/tiny_tds
        from C:/bin/ruby/233/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/bin/ruby/233/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.r
b:46:in `rescue in block in <top (required)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.r
b:43:in `block in <top (required)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.r
b:37:in `block in <top (required)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.r
b:34:in `block (2 levels) in <top (required)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.r
b:24:in `rescue in block in <top (required)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.r
b:17:in `block in <top (required)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.r
b:33:in `block in <top (required)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw3
2/lib/tiny_tds.rb:34:in `block (2 levels) in <top (required)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw3
2/lib/tiny_tds.rb:24:in `rescue in block in <top (required)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw3
2/lib/tiny_tds.rb:17:in `block in <top (required)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:33:in `block in <top (required)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:34:in `block (2 levels) in <top (requir
ed)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:24:in `rescue in block in <top (require
d)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:17:in `block in <top (required)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:33:in `block in <top (required)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:42:in `<top (required)>'
        from C:/bin/ruby/233/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from C:/bin/ruby/233/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from C:/bin/ruby/233/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'        from (irb):1
        from C:/bin/ruby/233/bin/irb.cmd:19:in `<main>'
```

**Comment by coderjoe** [comment]
@aharpervc you wouldn't happen to know the Windows version and architecture on which the above test was run, would you?

**Comment by aharpervc** [comment]
Yep, it's Windows 10 x64 `Version 1703 (OS Build 15063.674)`. Both ruby versions are 32bit.

**Comment by coderjoe** [comment]
Thanks. I'll take a look when next I have time.

**Comment by metaskills** [comment]
> It manifests the same way as various other issues in the past, where the library apparently can't be loaded:

Thanks. Just wanted to point out that manifested behavior is a bug and edge case to fix vs a signal of true compatibility. I'd like to find out why it does not work. Hopefully Joe has a handle on that :)

**Comment by aharpervc** [comment]
> Just wanted to point out that manifested behavior is a bug and edge case to fix vs a signal of true compatibility

This the behavior of the officially released gem. When I built it myself, I got a direct message indicating that only >= ruby 2.4 was supported. But actually you know what I'm just realizing, is that's because I only built the 2.4 version in my personal `native_gem.rake`. 😭 x 1000

Okay, yeah there's a problem then, I rescind all my min version comments.

**Comment by aharpervc** [comment]
Just rebuilt 2.1.0 for ruby 2.3 locally, installed, and got a similar but interestingly not identical error:

```
$ ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]

$ irb
irb(main):001:0> require 'tiny_tds'
LoadError: 126: The specified module could not be found.   - C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds/tiny_tds.so
```

The `.so` exists in that folder, so I guess something is subtly wrong with the build process? Not sure.

**Comment by coderjoe** [comment]
@aharpervc can you please double check that you have devkit in your path? Without devkit installed and in the path tiny_tds can not function due to the way the windows rubyinstaller packages ruby shared libraries.

A good test to see if devkit is installed properly or in the path is to `require 'devkit'` if you do not get a message about it initializing then something is probably not installed correctly.

**Comment by coderjoe** [comment]
@metaskills we spend enough time debugging these library load problems that we could probably benefit from automating the most common system checks for windows and posix (linux/osx) environments.

I've created issue #389 to cover what I think might be a good tooling addition.

**Comment by aharpervc** [comment]
Well how about that.

```
$ ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]

$ irb
irb(main):001:0> require 'tiny_tds'
LoadError: cannot load such file -- tiny_tds/tiny_tds
        from C:/bin/ruby/233/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/bin/ruby/233/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:46:in `rescue in block in <top (required)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:43:in `block in <top (required)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:37:in `block in <top (required)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:34:in `block (2 levels) in <top (required)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:24:in `rescue in block in <top (required)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:17:in `block in <top (required)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:33:in `block in <top (required)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:34:in `block (2 levels) in <top (required)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:24:in `rescue in block in <top (required)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:17:in `block in <top (required)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:33:in `block in <top (required)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:34:in `block (2 levels) in <top (required)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:24:in `rescue in block in <top (required)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:17:in `block in <top (required)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:33:in `block in <top (required)>'
        from C:/bin/ruby/233/lib/ruby/gems/2.3.0/gems/tiny_tds-2.1.0-x86-mingw32/lib/tiny_tds.rb:42:in `<top (required)>'
        from C:/bin/ruby/233/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from C:/bin/ruby/233/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from C:/bin/ruby/233/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from (irb):1
        from C:/bin/ruby/233/bin/irb.cmd:19:in `<main>'
irb(main):002:0> require 'devkit'
Temporarily enhancing PATH to include DevKit...
=> true
irb(main):003:0> require 'tiny_tds'
=> true
irb(main):004:0> TinyTds::VERSION
=> "2.1.0"
```

How about:

```diff
+ require 'tiny_tds
```

here:

https://github.com/rails-sqlserver/tiny_tds/blob/06e201934201b5f3293c6a000116012834135e47/lib/tiny_tds.rb#L11-L16

**Comment by coderjoe** [comment]
Did you mean `require 'devkit'`? If so version sniffing to auto-load devkit via `require 'devkit'` gets tricky. On some earlier versions of Ruby 2 for windows, depending on how you installed ruby, there were cases where you might not want to 'require `devkit`' and on Ruby 2.4 or greater you never want it. We could start doing version sniffing but I'm not sure I'm ready to commit to maintaining that until the ruby community collectively migrates to 2.4.

**Comment by aharpervc** [comment]
```ruby
  if Gem::Version.new(RUBY_VERSION) < Gem::Version.new('2.4')
    require 'devkit' rescue false
  end
```

**Comment by coderjoe** [comment]
That would probably work for many cases but I do not want to have to support or field issues caused by the `devkit.rb` site ruby file being loaded when it should not have been. 

To be absolutely clear, there are times where you would absolutely not want devkit to be loaded by default. This usually happens when ruby is bundled with 3rd party tools which have their own development/runtime environment that breaks when the devkit is required from within ruby.

In my experience this happens because `require 'devkit'` does more than just add devkit to the path. It also unconditionally overrides all of the ruby build environment variables which adds the potential for load-order dependency bugs to a gem if it is required.

**Comment by aharpervc** [comment]
Fair enough.

Why is it that devkit needs to be loaded at all? Why can't ruby load the `.so` without it? Why does this issue sometimes happen and sometimes not happen with this project (eg, why is it sometimes okay)?

**Comment by coderjoe** [comment]
@aharpervc That's a much longer discussion that I don't think is appropriate for a github issue. If you'd like to learn more you'll have to look into how dynamic library loading works in GCC and in the mingw toolset.

> Why is it that devkit needs to be loaded at all? Why can't ruby load the .so without it?

The TL;DR version is that one of the core libraries required by mingw/gcc for cross compiled dynamic libraries linking against gcc libgcc_s_sjlj-1.dll is not distributed by rubyinstaller by default. That file is only distributed with devkit. This was a decision made by the original rubyinstaller/devkit developers. Without that file cross compiled libraries can not properly load. It's just a side effect of how the ruby installer was distributed for many years.

> Why does this issue sometimes happen and sometimes not happen with this project (eg, why is it sometimes okay)?

Short version, it doesn't. That's selection bias. 
Long version is that there are only 6 possibilities:

1. Devkit is required and is not in the path/not set up. It doesn't work ever.
2. Devkit is required and it is properly configured. It always works.
3. Devkit is not required but is properly configured. It always works.
4. Devkit is not required and is not properly configured. It always works.
5. Devkit is no longer necessary at all because they removed the concept (ruby installer for 2.4+). It always works.
6. You're using an old version of tiny_tds which creates its own static/dynamic libraries and links against its own versions of openssl. It works... sometimes... based on windows memory utilization, GCC version, etc.

We were running into problems caused by 6, but that was fixed by removing the custom static/dynamic library linking for openssl in favor of the actual supported openssl build/linking process. That left only the problems caused by 1 left behind.

**Comment by aharpervc** [comment]
Great response, very helpful.

So one thing to potentially diagnose & confirm is, does my ruby 2.3.3 environment have devkit set up properly? The answer is appears to be "no", since if it was, I'd be able to `require` TinyTds 2.1.0 without issue, right?.

As for why older versions have installed in ruby 2.3.3 without issue (such as 1.0.5 and earlier in the 1.0.x series, which I still have installed), you're saying that was due to the change in how openssl is built. However, looking at the changelog, it doesn't seem like anything crazy was done here -- maybe back in 0.7.0, but I have used 1.0.5 on ruby 2.3.3 for a long time. What else could have changed here on 2.1.0? Technically this question could be answered with git bisect, but that would take a very long time to compute.

**Comment by coderjoe** [comment]
Custom DLL generation via dlltool was removed as it was causing library load problems with new versions of OpenSSL  in tiny_tds 2.0.0

https://github.com/rails-sqlserver/tiny_tds/commit/6e78d13c1f9eaee6c629c3664bcc4dcbcfeaa296#diff-3ca1da15253cb77126934ad2a353b5a1L183

**Comment by metaskills** [comment]
Are there other gems that have made the same decisions not to version sniff or the opposite and require devkit? Are there ways we can provide and ENV var to allow people to opt out if we did do the version sniff? More curious what others have done.

> That's a much longer discussion that I don't think is appropriate for a github issue.

FWIW, I am totally enjoying it :) F*ckin kudos for that write up too!!! Amazing learning here on my behalf. Thanks so much @coderjoe

**Comment by coderjoe** [comment]
FWIW a lot of examples of sniffing or just blindly including devkit can be found via: https://github.com/search?utf8=%E2%9C%93&q=%22require+%27devkit%27%22+extension%3Arb&type=Code

Most of the results are at the project level though, not the gem level.

**Comment by metaskills** [comment]
Thanks Joe, all really good links and ideas. Given that #390 is done, my vote would be to keep an eye out and figure out if work is needed later.
