### ISSUE TITLE
Calling a store procedure with parameters

### ISSUE THREAD

**Issue by Greek007** [rails-sqlserver/tiny_tds#395]
i'm trying to call a stored procedure  TDIMaster.Sp_CreateNewuserrole. this has 4 agruments .
so i tried the below code 
 if @connection.active?
(  result = @connection.execute("EXEC TDIMaster.Sp_CreateNewuserrole 'xxxx\\z00xxxx','TDIAdmin','test_only_new',0 " ) in this last argumet is int type .

this is failing to set a role for particular user. i'm getting below error

Transaction count after EXECUTE indicates a mismatching number of BEGIN and COMMIT statements. Previous count = 0, current count = 1.

can any one help me on this

**Comment by metaskills** [comment]
Start with something simple to ensure your connection is working. Like:

```ruby
@client.execute("SELECT 1 AS [one]").each
```

Then read the docs here for basic usage (https://github.com/rails-sqlserver/tiny_tds#tinytdsclient-usage), I can see your not calling `each` or `do` on the result object. Remember, start simple and debug upward. The error you are getting is likely due to something not related to TinyTDS, the first query will show that. Here are the docs for the procedure you are running too. https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-addrolemember-transact-sql
