### ISSUE TITLE
Always on encryption with SQL Server 2016

### ISSUE THREAD

**Issue by YvesR** [rails-sqlserver/tiny_tds#404]
Hello Ken,

I just run into this question:
Does tiny_tds support Always on encryption?

See this link https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/always-encrypted-database-engine.

I did not try, just want to know if pointless to try or give it a try.
Reason is new coming law (EU-DSGVO) which raise the pressure to make encryption by design.

Thanks for info!
Yves

**Comment by metaskills** [comment]
Great question. I have no idea but I would assume if they did make this change at the protocol layer, it would be behind some 7.4 flag in TDS similar to active directory https://github.com/rails-sqlserver/tiny_tds/issues/221

Are you able to test this? Also, the FreeTDS list might be a good place to check too since they are the source of all our powers.

**Comment by andyundso** [comment]
I am going to close this issue because of its age.

With #567, we actually have a test scenario that runs with "Always On Encryption", but only on Windows for now. But I would expect that since it works on Windows, it should also work well on Linux.
