### ISSUE TITLE
Unable to connect when upgrade to Rials 6

### ISSUE THREAD

**Issue by weijenlarryli** [rails-sqlserver/tiny_tds#518]
## Environment

**Operating System**
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"

**TinyTDS Version and Information**
tiny_tds (2.1.2)    
I also tried 2.1.5

**FreeTDS Version**
MS db-lib source compatibility: no
        Sybase binary compatibility: yes
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 4.2
                              iODBC: no
                           unixodbc: yes
              SSPI "trusted" logins: no
                           Kerberos: yes

## Description
I have used Rails 5 with TinyTds gem to connect to many servers. (hundreds of them)
I recently upgrated to Rails 6. My system can connect to most of the servers, but cannot connect to some.
When I start a client side, I get this error:
```
TinyTds::Error: Unable to connect: Adaptive Server is unavailable or does not exist (some.server.address:1433)
from ....gems/tiny_tds-2.1.2/lib/tiny_tds/client.rb:60:in `connect'
```

Is there any way to figure out why I cannot connect?
I can connect when I switch back to Rails 5.

Thanks.

**Comment by aharpervc** [comment]
TinyTDS can't really tell you anything that FreeTDS isn't already saying; ie, it can't connect for some reason. The diagnostics are up to you. Here's some ideas to get you started:

1. Is the FreeTDS info otherwise identical?
2. Is the TDS version the same (4.2 is very old)
3. Can you connect to from this web server to that SQL Server instance using other tools (eg, `tsql`)
4. Does the SQL Server log show anything interesting when you try to connect?

**Comment by weijenlarryli** [comment]
1. Yes they are identical. 
2. The version seems old. Are the versions backward compatible?
3. Yes, I can connect using command like tsql -S [hostname] -U [user] -P [password]
     But unable to connect using TinyTds::Client from rails_console.
5. Have not been able to see the SQL server logs. I will try this.

**Comment by weijenlarryli** [comment]
Adding a follow up to this. 
Here are discussions and solutions:
https://github.com/FreeTDS/freetds/issues/336
https://github.com/FreeTDS/freetds/issues/299

**Comment by andyundso** [comment]
as a summary from the issue @weijenlarryli linked:

* specifying TDS v7.0 manually seems to solve the issue since TDS v7.0 does not support encryption.
* Linux generally drops support for older ciphers faster than Windows. So if your Linux system and the MSSQL Windows server do not find a matching cipher, the connection could be dropped. Try to look into `DEFAULT:@SECLEVEL` configuration option in OpenSSL.
* Some people started to compile FreeTDS against GnuTLS instead of OpenSSL.
